<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>WinExe</OutputType>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DuEDrawingControl" Version="1.0.3" />
  </ItemGroup>
</Project>